"""Family / Caregiver Access module aggregate root: `FamilyAccess`.

References `Patient` (`patient_id`) and the caregiver `User`
(`caregiver_user_id`) as peers by ID only (never an object reference) —
validated by the application layer via those modules' public
`PatientQueryPort`/`UserQueryPort` (see
`application/use_cases/invite_caregiver.py`), never by importing across
`domain/` packages, the same rule every prior module's own entity
docstring states.

**`invitation_token` stores a SHA-256 hash, never the raw token.** This
mirrors `app.modules.authentication.domain.entities.RefreshToken
.token_hash` exactly: an invitation token is already a high-entropy,
randomly generated value (see
`app.core.security.invitation_token_hashing`), not a user-chosen secret,
so a fast deterministic digest is both sufficient and necessary (a
salted KDF like bcrypt would make "look this invitation up by its token"
impossible without iterating every row). The raw token is generated by
`InviteCaregiver`, returned to the caller exactly once, and never
persisted anywhere — a caller who loses it cannot recover it, only
re-invite. The field is named `invitation_token` (not
`invitation_token_hash`) per this task's own Entity specification; its
*value* is always an `InvitationTokenHash`.

**Status transitions are a branching graph, not a linear chain** —
`Pending` fans out to `Accepted`/`Rejected`/`Revoked`/`Expired`, and only
`Accepted` has a further outgoing edge (`-> Revoked`); every other status
is terminal. This is the exact shape
`app.modules.notification.domain.entities.Notification` already
establishes via a `dict[Status, frozenset[Status]]` map (not the
strictly-linear `dict[Status, Status]` `app.modules.documents.domain
.entities.MedicalDocument` uses for its own single-path chain) — see
`_ALLOWED_TRANSITIONS` below.

**`accept()`/`revoke()` take `now` as an explicit keyword parameter**
rather than calling `datetime.now(UTC)` internally. Two precedents exist
in this codebase for "how does a domain method learn the current time":
`Notification.mark_sent()` calls `datetime.now(UTC)` directly (documented
there as "not I/O, so it does not violate the domain layer's own no-I/O
rule"), while `app.modules.authentication.domain.entities.RefreshToken
.rotate()`/`.is_active()` take `now` as an explicit parameter instead.
This entity follows the latter: `accept()`'s whole purpose is comparing
"now" against `invitation_expires_at`, so threading it in from the
application layer (which already needs to compute `now` once, e.g. to
derive `invitation_expires_at` when inviting) keeps that comparison
trivially unit-testable without monkeypatching `datetime.now`.

**Expiration has no background-job sweep** (explicitly out of scope for
this task): `accept()` checks `invitation_expires_at` against `now` and
raises `InvitationExpiredError` *without* silently transitioning the
grant to `Expired` itself — the same choice `Notification.mark_sent()`
already documents ("a future caller — a Background Job sweep, once
built, or a manual administrative action — is expected to decide for
itself when to call" the dedicated `expire()`/`mark_expired()` method).
`expire()` is exposed here for exactly that future caller; nothing in
this task's own use cases calls it.

All mutation goes through named methods that enforce the aggregate's
invariants and record domain events; nothing here performs I/O.
"""

from dataclasses import dataclass
from datetime import datetime
from uuid import UUID

from app.modules.family_access.domain.enums import AccessLevel, FamilyAccessStatus, Relationship
from app.modules.family_access.domain.events import FamilyAccessInvited, FamilyAccessStatusChanged
from app.modules.family_access.domain.exceptions import (
    InvalidFamilyAccessStatusTransitionError,
    InvitationExpiredError,
)
from app.modules.family_access.domain.value_objects import InvitationTokenHash
from app.shared.domain.entity import AggregateRoot

_ALLOWED_TRANSITIONS: dict[FamilyAccessStatus, frozenset[FamilyAccessStatus]] = {
    FamilyAccessStatus.PENDING: frozenset(
        {
            FamilyAccessStatus.ACCEPTED,
            FamilyAccessStatus.REJECTED,
            FamilyAccessStatus.REVOKED,
            FamilyAccessStatus.EXPIRED,
        }
    ),
    FamilyAccessStatus.ACCEPTED: frozenset({FamilyAccessStatus.REVOKED}),
    FamilyAccessStatus.REJECTED: frozenset(),
    FamilyAccessStatus.REVOKED: frozenset(),
    FamilyAccessStatus.EXPIRED: frozenset(),
}


@dataclass(kw_only=True, eq=False)
class FamilyAccess(AggregateRoot):
    organization_id: UUID
    patient_id: UUID
    caregiver_user_id: UUID
    relationship: Relationship
    access_level: AccessLevel
    invitation_token: InvitationTokenHash
    invitation_expires_at: datetime
    status: FamilyAccessStatus = FamilyAccessStatus.PENDING
    accepted_at: datetime | None = None
    revoked_at: datetime | None = None
    notes: str | None = None

    @classmethod
    def create(
        cls,
        *,
        organization_id: UUID,
        patient_id: UUID,
        caregiver_user_id: UUID,
        relationship: Relationship,
        access_level: AccessLevel,
        invitation_token: InvitationTokenHash,
        invitation_expires_at: datetime,
        notes: str | None = None,
    ) -> "FamilyAccess":
        grant = cls(
            organization_id=organization_id,
            patient_id=patient_id,
            caregiver_user_id=caregiver_user_id,
            relationship=relationship,
            access_level=access_level,
            invitation_token=invitation_token,
            invitation_expires_at=invitation_expires_at,
            notes=notes,
        )
        grant.record_event(
            FamilyAccessInvited(
                family_access_id=grant.id,
                organization_id=organization_id,
                patient_id=patient_id,
                caregiver_user_id=caregiver_user_id,
            )
        )
        return grant

    def accept(self, *, now: datetime) -> None:
        """`Pending -> Accepted`. See the module docstring for why the
        transition-validity check runs before the expiry check, and why
        an expired grant is left `Pending` rather than auto-transitioned
        to `Expired` here."""
        allowed = _ALLOWED_TRANSITIONS.get(self.status, frozenset())
        if FamilyAccessStatus.ACCEPTED not in allowed:
            raise InvalidFamilyAccessStatusTransitionError(
                self.status.value, FamilyAccessStatus.ACCEPTED.value
            )
        if now >= self.invitation_expires_at:
            raise InvitationExpiredError(self.id)
        self._transition_to(FamilyAccessStatus.ACCEPTED)
        self.accepted_at = now

    def reject(self) -> None:
        """`Pending -> Rejected`. Unlike `accept()`, rejecting carries no
        expiry check — this task's own business rule states only that
        "expired invitations cannot be accepted", not that they cannot
        be declined."""
        self._transition_to(FamilyAccessStatus.REJECTED)

    def revoke(self, *, now: datetime) -> None:
        """`(Pending|Accepted) -> Revoked`. Revoked access can never be
        restored — enforced structurally: `Revoked` has no outgoing
        edges in `_ALLOWED_TRANSITIONS`."""
        self._transition_to(FamilyAccessStatus.REVOKED)
        self.revoked_at = now

    def expire(self) -> None:
        """`Pending -> Expired`. No caller in this task invokes this —
        see the module docstring."""
        self._transition_to(FamilyAccessStatus.EXPIRED)

    def _transition_to(self, target_status: FamilyAccessStatus) -> None:
        allowed = _ALLOWED_TRANSITIONS.get(self.status, frozenset())
        if target_status not in allowed:
            raise InvalidFamilyAccessStatusTransitionError(self.status.value, target_status.value)
        old_status = self.status
        self.status = target_status
        self.touch()
        self.record_event(
            FamilyAccessStatusChanged(
                family_access_id=self.id, old_status=old_status, new_status=target_status
            )
        )
